{% set name = "agemo" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/agemo-{{ version }}.tar.gz
  sha256: 0ca85f60f43335f5934907374d2c7d0171cfbc2cfaae7fbc113202e5b814feb1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - numpy <1.22,>=1.18
    - numba >=0.54.0

test:
  imports:
    - agemo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LohseLab/agemo
  summary: Laplace transformed coalescence times
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://agemo.readthedocs.io/

extra:
  recipe-maintainers:
    - GertjanBisschop
